### ISSUE TITLE
Remake the scheme (status)

### ISSUE THREAD

**Issue by chawyehsu** [chawyehsu/base16-github-scheme#1]
variant 1:
```yaml
scheme: "Github Light"
base00: "ffffff" 
base01: "f5f5f5" 
base02: "e8e8e8" 
base03: "6a737d" 
base04: "586069" 
base05: "444d56" 
base06: "24292e" 
base07: "24292e" 
base08: "24292e" 
base09: "005cc5" 
base0A: "6f42c1" 
base0B: "032f62" 
base0C: "032f62" 
base0D: "005cc5" 
base0E: "d73a49" 
base0F: "24292e" 
```

![preview Github Light](https://user-images.githubusercontent.com/5764917/76695951-4ffdab80-66c0-11ea-8819-b6b71c3aa32b.png)

![2018-08-29_193503](https://user-images.githubusercontent.com/5764917/44785287-f6f42280-abc2-11e8-80d1-1758594b4b06.jpg)

Not good enough.
